image: ubuntu:rolling
stages:
    - .pre
    - test

before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
    - apt-get install python3 python3-pip git libsm6 libxext6 ffmpeg -y
    - python3 -m pip install --upgrade pip
    - python3 -m pip install .
    - python3 -m pip install yapf pytest pytest-cov

Lint-with-yapf:
    stage: test
    script:
        - ./.github/check_code_formatting.sh

Test-with-pytest:
    stage: test
    script:
        - ./.github/run_tests.sh
