image: debian:latest
stages:
    - test

before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
    - apt-get install python3 python3-pip git libsm6 libxext6 ffmpeg -y
    - pip3 install --break-system-packages --upgrade pip
    - pip3 install --break-system-packages .
    - pip3 install --break-system-packages yapf pytest pytest-cov

Lint-with-yapf:
    stage: test
    script:
        - ./.github/check_code_formatting.sh

Test-with-pytest:
    stage: test
    script:
        - ./.github/run_tests.sh
    artifacts:
        when: on_failure
        paths:
            - ./tests/logs

Documentation:
    stage: test
    image: $CI_DOCS_DOCKER_IMAGE
    tags:
        - docs
    variables:
        DOCS_DIR: 'docs'
    before_script:
        - echo "Building the documentation"
    script:
        - cd $DOCS_DIR
        - pip3 install -r requirements.txt
        - make html latexpdf
        - cp build/latex/*.pdf build/html
        - tar cf ../$CI_DOCS_ARCHIVE -C build/html/ .
    artifacts:
        paths:
            - $DOCS_DIR/build
            - $CI_DOCS_ARCHIVE

Test-performance:
    stage: test
    script:
        - ./.github/performance.sh

Test-prediction:
    stage: test
    script:
        - ./.github/prediction_test.sh